name: responsive_spacing_v2
description: "A simple Flutter package to add responsive padding and margin widgets for consistent, adaptive spacing across different screen sizes."
version: 1.1.1
homepage: https://github.com/Nishan-Pradhan06/responsive_spacing

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

